### PR TITLE
More subject_alt_* accessors.

### PR DESCRIPTION
**Pull request by psagers**
And a streamlined implementation.

### CODE REVIEW

**Comment by wbond** [comment]
The docs should be generated by the `api_docs` task, however I don't think that will be possible with the proposed code where there are no `def` keywords to fetch the docstring of.

**Comment by psagers** [comment]
Ah, sure enough. I didn't realize that was auto-generated. Are you avoiding Sphinx or just not familiar with it?

**Comment by wbond** [comment]
Sphinx was over complicated for what I wanted, which was just some basic markdown generation from docstrings.

**Comment by wbond** [comment]
I know it isn't as compact as what you wrong, but I added these in 7949183d71bdc6130a387c08dea645af2b910dbf. The upside being the doc generation.

Thanks for taking the effort to have these added!

**Comment by wbond** [comment]
These attributes are part of version 0.13.0, FYI

**Comment by psagers** [comment]
Thanks! Have you thought about distributing [wheels](http://pythonwheels.com/) in addition to sdists? It's a rather more sensible and efficient format for installing.

**Comment by wbond** [comment]
How are they treated differently by pip?

**Comment by wbond** [comment]
I guess the follow on would be, are you using something other than pip?

**Comment by psagers** [comment]
pip loves wheels and prefers them over sdist.

https://pip.pypa.io/en/stable/user_guide/#installing-from-wheels

**Comment by wbond** [comment]
Hmm, seems that I'd have to general multiple wheels to get the coverage that the current `tar.gz` covers. Is there a major performance difference installing from a wheel than a `tar.gz`?

**Comment by psagers** [comment]
For pure-python packages that build the same for py2 and py3 (same setup() arguments), you just need one wheel: `python setup.py sdist bdist_wheel --universal upload` Or add this to your setup.cfg:

```
[bdist_wheel]
universal = 1
```

Upload with [twine](https://pypi.python.org/pypi/twine) for improved security.

Wheels are both faster and more deterministic, because there's no setup.py to run at install time, traversing package trees and importing god knows what. It's just a list of files and static metadata about what to do with them.

**Comment by wbond** [comment]
I have been using twine, but the docs/info on wheels never really seemed to focus on anything but packages with binary components.

I've added a new task to oscrypto to automate the process of creating releases, and I've added params so that a universal wheel is built also. I'll work on porting this to the other modularcrypto packages, including this one.

Thanks for taking the time to explain why you are interested in it, and providing some pointers.

**Pull request closed without merging**
